# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fhat <- function(X, N, K, Rsel, stdz) {
    .Call(`_fEBAcpp_fhat`, X, N, K, Rsel, stdz)
}

ghat <- function(fhat) {
    .Call(`_fEBAcpp_ghat`, fhat)
}

Qpval <- function(fhat, K, ndraw, Qts, Qint, blockdiag) {
    .Call(`_fEBAcpp_Qpval`, fhat, K, ndraw, Qts, Qint, blockdiag)
}

fEBA <- function(fhat, ghat, K, ndraw, alpha, blockdiag) {
    .Call(`_fEBAcpp_fEBA`, fhat, ghat, K, ndraw, alpha, blockdiag)
}

rcpparma_hello_world <- function() {
    .Call(`_fEBAcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_fEBAcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_fEBAcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_fEBAcpp_rcpparma_bothproducts`, x)
}

